services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./back:/app
    command: npm run start

  front:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - ./front:/app
    # command: npm run dev
    depends_on:
      - back